CREATE PROCEDURE DESACTIVAR_CATEGORIA
  @IdCategoria UNIQUEIDENTIFIER,
  @EstadoId INT
AS
BEGIN
  SET NOCOUNT ON;

  UPDATE dbo.CATEGORIAS
  SET ESTADO_ID = @EstadoId
  WHERE CATEGORIAS_ID = @IdCategoria;

  SELECT @IdCategoria;
END;
