CREATE PROCEDURE ELIMINAR_PRODUCTO
  @IdProducto UNIQUEIDENTIFIER
AS
BEGIN
  SET NOCOUNT ON;

  BEGIN TRANSACTION;

  DELETE FROM [dbo].[PRODUCTOS]
  WHERE PRODUCTOS_ID = @IdProducto;

  COMMIT TRANSACTION;

  SELECT @IdProducto AS Eliminado;
END;
