CREATE PROCEDURE ELIMINAR_PROVEEDOR
    @ProveedorId  UNIQUEIDENTIFIER
AS
BEGIN
  SET NOCOUNT ON;

  BEGIN TRANSACTION;

    DELETE FROM [dbo].[Proveedores]
        WHERE PROVEEDOR_ID = @ProveedorId;
  COMMIT TRANSACTION;

  SELECT @ProveedorId  AS Eliminado;
END;
