CREATE PROCEDURE ELIMINAR_CARRITOPRODUCTO
    @CarritoProductoId UNIQUEIDENTIFIER
AS
BEGIN
  SET NOCOUNT ON;

  BEGIN TRANSACTION;

DELETE FROM [dbo].[CARRITO_PRODUCTO]
  WHERE CARRITO_PRODUCTO_ID = @CarritoProductoId;

  COMMIT TRANSACTION;

  SELECT @CarritoProductoId AS Eliminado;
END;
