CREATE PROCEDURE VER_PRODUCTO_POR_ID
  @IdProducto UNIQUEIDENTIFIER
AS
BEGIN
  SET NOCOUNT ON;

  SELECT 
    P.PRODUCTOS_ID AS IdProducto,
    P.NOMBRE AS Nombre,
    P.PRECIO AS Precio,
    P.DESCRIPCION AS Descripcion,
    P.STOCK AS Stock,
    P.IMAGEN_URL AS ImagenUrl,
    P.FECHA_CREACION AS FechaCreacion,
    CONCAT(U.NOMBRE, ' ', U.APELLIDO) AS NombreProveedor,
    C.NOMBRE AS Categoria,
    E.TIPO AS Estado

  FROM PRODUCTOS P
  INNER JOIN USUARIOS U ON P.USUARIO_ID = U.USUARIOS_ID
  INNER JOIN CATEGORIAS C ON P.CATEGORIAS_ID = C.CATEGORIAS_ID
  INNER JOIN ESTADOS E ON P.ESTADO_ID = E.ESTADO_ID
  WHERE P.PRODUCTOS_ID = @IdProducto;
END;