CREATE PROCEDURE VER_CATEGORIA_POR_ID
  @IdCategoria UNIQUEIDENTIFIER
AS
BEGIN
  SET NOCOUNT ON;

  SELECT 
    C.CATEGORIAS_ID AS IdCategoria,
    C.NOMBRE AS Nombre,
    C.DESCRIPCION AS Descripcion,
    C.FECHA_CREACION AS FechaCreacion,
     C.ESTADO_ID AS EstadoId  
  FROM CATEGORIAS C
  INNER JOIN ESTADOS E ON C.ESTADO_ID = E.ESTADO_ID
  WHERE C.CATEGORIAS_ID = @IdCategoria;
END;
