CREATE TABLE [dbo].[CARRITO_PRODUCTO]
(
  [CARRITO_PRODUCTO_ID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
  CARRITO_ID UNIQUEIDENTIFIER not null,
  CANTIDAD INT NOT NULL,
  TOTAL_LINEA DECIMAL(8,2) NOT NULL,
  FOREIGN KEY (CARRITO_ID) REFERENCES CARRITO(CARRITO_ID)
  )