  CREATE TABLE [dbo].[CARRITO]
(
  [CARRITO_ID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
  USUARIO_ID UNIQUEIDENTIFIER not null,
  FECHA_CREACION DATE NOT NULL,
  TOTAL DECIMAL(8,2) NOT NULL,
  FOREIGN KEY (USUARIO_ID) REFERENCES Usuarios([USUARIOS_ID])
  )