  CREATE TABLE [dbo].[CATEGORIA_X_CATEGORIA]
(
  [CXC_ID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
  [PADRE_ID] UNIQUEIDENTIFIER NOT NULL,
  [HIJO_ID] UNIQUEIDENTIFIER NOT NULL,
  FOREIGN KEY (PADRE_ID) REFERENCES CATEGORIAS(CATEGORIAS_ID),
  FOREIGN KEY (HIJO_ID) REFERENCES CATEGORIAS(CATEGORIAS_ID),
  CONSTRAINT UQ_CATEGORIA_RELACION_UNICA UNIQUE (PADRE_ID, HIJO_ID)
);

