  CREATE TABLE [dbo].[CATEGORIAS]
(
  [CATEGORIAS_ID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
  NOMBRE NVARCHAR(255) not null,
  FECHA_CREACION DATE NOT NULL,
  DESCRIPCION NVARCHAR(255),
  ESTADO_ID int NOT NULL,
  FOREIGN KEY (ESTADO_ID) REFERENCES ESTADOS(ESTADO_ID)
  )
