CREATE TABLE [dbo].[PRODUCTOS]
(
  [PRODUCTOS_ID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
  NOMBRE NVARCHAR(255) not null,
  PRECIO DECIMAL(8,2) NOT NULL,
  DESCRIPCION NVARCHAR(255),
  USUARIO_ID UNIQUEIDENTIFIER NOT NULL,
  CATEGORIAS_ID UNIQUEIDENTIFIER NOT NULL,
  STOCK INT NOT NULL,
  IMAGEN_URL NVARCHAR(255),
  FECHA_CREACION DATE NOT NULL,
  ESTADO_ID int NOT NULL,
  FOREIGN KEY (USUARIO_ID) REFERENCES Usuarios([USUARIOS_ID]),
  FOREIGN KEY (ESTADO_ID) REFERENCES ESTADOS(ESTADO_ID),
  FOREIGN KEY (CATEGORIAS_ID) REFERENCES CATEGORIAS(CATEGORIAS_ID)
  )