
CREATE TABLE [dbo].[Usuarios]
(
  [USUARIOS_ID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
  NOMBRE NVARCHAR(255) not null,
  APELLIDO NVARCHAR(255) not null,
  CORREO VARCHAR(255) UNIQUE NOT NULL,
  PASS_HASH NVARCHAR(256),
  IMAGEN_URL NVARCHAR(256),
  TELEFONO VARCHAR(10) NOT NULL,
  DIRECCION NVARCHAR(256),
  FECHA_CREACION DATE NOT NULL,
  ESTADO_ID int NOT NULL,
  FOREIGN KEY (ESTADO_ID) REFERENCES ESTADOS(ESTADO_ID)
)