CREATE TABLE [dbo].[USUARIOS_ROLES]
(
  [USUARIOS_ROLES_ID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
  USUARIO_ID UNIQUEIDENTIFIER NOT NULL,
  ROLES_ID UNIQUEIDENTIFIER NOT NULL,
  FOREIGN KEY (USUARIO_ID) REFERENCES Usuarios([USUARIOS_ID]),
  FOREIGN KEY (ROLES_ID) REFERENCES ROLES(ROLES_ID),
  )

